# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{textractor}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Guterl"]
  s.date = %q{2010-07-27}
  s.description = %q{simple wrapper around CLI for extracting text from PDF and Word documents}
  s.email = %q{mguterl@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/textractor.rb",
     "lib/textractor/document.rb",
     "spec/document_spec.rb",
     "spec/fixtures/document.doc",
     "spec/fixtures/document.docx",
     "spec/fixtures/document.pdf",
     "spec/fixtures/document.txt",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/textractor_spec.rb",
     "support/wvText.xml",
     "textractor.gemspec",
     "vendor/docx2txt/AUTHORS",
     "vendor/docx2txt/BSDmakefile",
     "vendor/docx2txt/COPYING",
     "vendor/docx2txt/ChangeLog",
     "vendor/docx2txt/INSTALL",
     "vendor/docx2txt/Makefile",
     "vendor/docx2txt/README",
     "vendor/docx2txt/ToDo",
     "vendor/docx2txt/VERSION",
     "vendor/docx2txt/WInstall.bat",
     "vendor/docx2txt/docx2txt.bat",
     "vendor/docx2txt/docx2txt.config",
     "vendor/docx2txt/docx2txt.pl",
     "vendor/docx2txt/docx2txt.sh",
     "vendor/docx2txt/resume.docx"
  ]
  s.homepage = %q{http://github.com/mguterl/textractor}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{simple wrapper around CLI tools for extracting text from PDF and Word documents}
  s.test_files = [
    "spec/document_spec.rb",
     "spec/spec_helper.rb",
     "spec/textractor_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
  end
end

